import type { Role } from "@/shared/types"

/* LCU assignedPosition → display role (prototype uses Top/Jungle/Mid/Bot/Support) */
export type DisplayRole = "Top" | "Jungle" | "Mid" | "Bot" | "Support"

const BY_POSITION: Record<string, DisplayRole> = {
	top: "Top",
	jungle: "Jungle",
	middle: "Mid",
	bottom: "Bot",
	utility: "Support",
}

export function displayRole(assignedPosition: string): DisplayRole | null {
	return BY_POSITION[assignedPosition] ?? null
}

export const ROLE_ABBR: Record<DisplayRole, string> = {
	Top: "TOP",
	Jungle: "JNG",
	Mid: "MID",
	Bot: "BOT",
	Support: "SUP",
}

/* role-glyph dot positions on the diagonal (champ-art.jsx:468) */
export const ROLE_GLYPH_POS: Record<DisplayRole, [number, number]> = {
	Top: [6, 6],
	Jungle: [9, 14],
	Mid: [12, 12],
	Bot: [18, 18],
	Support: [15, 19],
}

export const CHAMPION_LANE: Record<string, DisplayRole> = {
	Aatrox: "Top",
	Ahri: "Mid",
	Akali: "Mid",
	Akshan: "Mid",
	Alistar: "Support",
	Ambessa: "Top",
	Amumu: "Jungle",
	Anivia: "Mid",
	Annie: "Mid",
	Aphelios: "Bot",
	Ashe: "Bot",
	AurelionSol: "Mid",
	Aurora: "Mid",
	Azir: "Mid",
	Bard: "Support",
	Belveth: "Jungle",
	Blitzcrank: "Support",
	Brand: "Support",
	Braum: "Support",
	Briar: "Jungle",
	Caitlyn: "Bot",
	Camille: "Top",
	Cassiopeia: "Mid",
	Chogath: "Top",
	Corki: "Mid",
	Darius: "Top",
	Diana: "Jungle",
	DrMundo: "Top",
	Draven: "Bot",
	Ekko: "Mid",
	Elise: "Jungle",
	Evelynn: "Jungle",
	Ezreal: "Bot",
	Fiddlesticks: "Jungle",
	Fiora: "Top",
	Fizz: "Mid",
	Galio: "Mid",
	Gangplank: "Top",
	Garen: "Top",
	Gnar: "Top",
	Gragas: "Jungle",
	Graves: "Jungle",
	Gwen: "Top",
	Hecarim: "Jungle",
	Heimerdinger: "Mid",
	Hwei: "Mid",
	Illaoi: "Top",
	Irelia: "Top",
	Ivern: "Jungle",
	Janna: "Support",
	JarvanIV: "Jungle",
	Jax: "Top",
	Jayce: "Top",
	Jhin: "Bot",
	Jinx: "Bot",
	Kaisa: "Bot",
	Kalista: "Bot",
	Karma: "Support",
	Karthus: "Jungle",
	Kassadin: "Mid",
	Katarina: "Mid",
	Kayle: "Top",
	Kayn: "Jungle",
	Kennen: "Top",
	Khazix: "Jungle",
	Kindred: "Jungle",
	Kled: "Top",
	KogMaw: "Bot",
	KSante: "Top",
	Leblanc: "Mid",
	LeeSin: "Jungle",
	Leona: "Support",
	Lillia: "Jungle",
	Lissandra: "Mid",
	Lucian: "Bot",
	Lulu: "Support",
	Lux: "Support",
	Malphite: "Top",
	Malzahar: "Mid",
	Maokai: "Support",
	MasterYi: "Jungle",
	Mel: "Mid",
	Milio: "Support",
	MissFortune: "Bot",
	MonkeyKing: "Jungle",
	Mordekaiser: "Top",
	Morgana: "Support",
	Naafiri: "Mid",
	Nami: "Support",
	Nasus: "Top",
	Nautilus: "Support",
	Neeko: "Mid",
	Nidalee: "Jungle",
	Nilah: "Bot",
	Nocturne: "Jungle",
	Nunu: "Jungle",
	Olaf: "Jungle",
	Orianna: "Mid",
	Ornn: "Top",
	Pantheon: "Top",
	Poppy: "Jungle",
	Pyke: "Support",
	Qiyana: "Mid",
	Quinn: "Top",
	Rakan: "Support",
	Rammus: "Jungle",
	RekSai: "Jungle",
	Rell: "Support",
	Renata: "Support",
	Renekton: "Top",
	Rengar: "Jungle",
	Riven: "Top",
	Rumble: "Top",
	Ryze: "Mid",
	Samira: "Bot",
	Sejuani: "Jungle",
	Senna: "Support",
	Seraphine: "Support",
	Sett: "Top",
	Shaco: "Jungle",
	Shen: "Top",
	Shyvana: "Jungle",
	Singed: "Top",
	Sion: "Top",
	Sivir: "Bot",
	Skarner: "Jungle",
	Smolder: "Bot",
	Sona: "Support",
	Soraka: "Support",
	Swain: "Support",
	Sylas: "Mid",
	Syndra: "Mid",
	TahmKench: "Support",
	Taliyah: "Jungle",
	Talon: "Mid",
	Taric: "Support",
	Teemo: "Top",
	Thresh: "Support",
	Tristana: "Bot",
	Trundle: "Jungle",
	Tryndamere: "Top",
	TwistedFate: "Mid",
	Twitch: "Bot",
	Udyr: "Jungle",
	Urgot: "Top",
	Varus: "Bot",
	Vayne: "Bot",
	Veigar: "Mid",
	Velkoz: "Support",
	Vex: "Mid",
	Vi: "Jungle",
	Viego: "Jungle",
	Viktor: "Mid",
	Vladimir: "Mid",
	Volibear: "Jungle",
	Warwick: "Jungle",
	Xayah: "Bot",
	Xerath: "Support",
	XinZhao: "Jungle",
	Yasuo: "Mid",
	Yone: "Mid",
	Yorick: "Top",
	Yuumi: "Support",
	Zac: "Jungle",
	Zed: "Mid",
	Zeri: "Bot",
	Ziggs: "Mid",
	Zilean: "Support",
	Zoe: "Mid",
	Zyra: "Support",
}

export function championLane(id: string): DisplayRole | null {
	return CHAMPION_LANE[id] ?? null
}

/* Role (lowercase, shared contract) ↔ DisplayRole (renderer) ↔ OP.GG position enum */
const ROLE_TO_DISPLAY: Record<Role, DisplayRole> = {
	top: "Top",
	jungle: "Jungle",
	middle: "Mid",
	bottom: "Bot",
	utility: "Support",
}

const DISPLAY_TO_ROLE: Record<DisplayRole, Role> = {
	Top: "top",
	Jungle: "jungle",
	Mid: "middle",
	Bot: "bottom",
	Support: "utility",
}

const ROLE_TO_POSITION: Record<Role, string> = {
	top: "TOP",
	jungle: "JUNGLE",
	middle: "MID",
	bottom: "ADC",
	utility: "SUPPORT",
}

export function roleToDisplay(role: Role): DisplayRole {
	return ROLE_TO_DISPLAY[role]
}

export function displayToRole(role: DisplayRole): Role {
	return DISPLAY_TO_ROLE[role]
}

export function roleToPosition(role: Role): string {
	return ROLE_TO_POSITION[role]
}
